config/routes.rb
# ルーティングの設定
Rails.application.routes.draw do
  
  get 'sessions/new'
  
  root 'pages#index'
  get 'pages/help'
  
  get    '/login',   to: 'sessions#new' 
  # ログインするためのフォームを表示するページの取得
  
  post   '/login',   to: 'sessions#create'
  # ログイン時に新しいアドレスやパスワードを送信してもらい、Sessionの作成する
  
  delete '/logout',   to: 'sessions#destroy'
  # ログアウト時にSessionを削除する
  
  resources :users
  resources :topics
  
  get 'favorites/index'
  post '/favorites', to: 'favorites#create'
  
  delete '/favorites', to: 'favorites#destroy'
  
  resources :comments
  
  get 'comments/new'
  post '/comments', to: 'comments#create'
  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :user_id, presence: true
  validates :topic_id, presence: true
  validates :description, presence: true
  
  belongs_to :user
  belongs_to :topics
  
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :topic
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates :user_id, presence: true
  validates :description, presence: true
  validates :image, presence: true
  
  belongs_to :user
  
  mount_uploader :image, ImageUploader

  has_many :favorites
  has_many :favorite_users, through: :favorites, source: 'user'
  has_many :comments
  
end

app/models/user.rb
# userモデルを扱う、userデータ条件を決定する

class User < ApplicationRecord
  # 名前を15文字まで許可を追加
  validates :name, presence: true, length: { maximum: 15 }

  # ~ @ ~ . ~の形を許可
  VALID_EMAIL_REGEX = /\A\S+@\S+\.\S+\z/
  # /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/
  # /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }
  
  # アルファベット、数字の混合のみ可能
  VALID_PASSWRD_REGEX =/\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/
  # /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{8,32}+\z/i
  
  # パスワードの文字数制限
  validates :password, presence: true, length: { minimum: 8, maximum: 32 }, format: { with: VALID_PASSWRD_REGEX }
  # minimum: 8, maximum: 32
  
  has_secure_password
  
  has_many :topics
  has_many :favorites
  has_many :favorite_topics, through: :favorites, source: 'topic'
  has_many :comments
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  add_flash_types :success, :info, :warning, :danger
  
  helper_method :current_user, :logged_in? # ★課題
  
  def current_user # 現在ログインしているユーザーを返す
    @current_user ||= User.find_by(id:session[:user_id])
  end
  
  def logged_in? # ログインしているかどうかの確認メソッド
    !current_user.nil?
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def new
    @comment = Comment.new
    @topic = Topic.find(params[:topic_id])
  end
  
  def create
    @comment = current_user.comments.new(comment_params)
    
    #binding.pry
    
    if @comment.save
      redirect_to comments_path, success: 'コメントしました'
      
    else
      flash.now[:danger] = "コメントできませんでした"
      render :new
    end
  end
    
    private
    def comment_params
      params.require(:comment).permit(:topic_id, :description)
    end
  
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @favorite_topics = current_user.favorite_topics
  end
  
  
  def create
    favorite = Favorite.new
    favorite.user_id = current_user.id
    favorite.topic_id = params[:topic_id]
    
    #binding.pry
    
    if favorite.save
      redirect_to topics_path, success: 'お気に入りに登録しました'
        
    else
      redirect_to topics_path, danger: 'お気に入り登録に失敗しました'
    end
    
  end
  
  def destroy
    @favorite = Favorite.find_by(user_id: current_user.id, topic_id: params[:topic_id])
    @favorite.destroy
    redirect_to topics_path, success: 'お気に入りを取り消しました'
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
  
  def help
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  #binding.pry
  
  def create
    
    user = User.find_by(email: email_params[:email])  # ★課題
    # フォームに入力されたアドレスが一致するユーザーがいるか検索
   
    if user && user.authenticate(password_params[:password])  # ★課題
      # userのパスワードが正しいか確認
      log_in user
      redirect_to root_path, success: 'ログインに成功しました'
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end
  
  def destroy
    log_out
    redirect_to root_url, info: 'ログアウトしました'
  end
  
  private
  def log_in(user)
    session[:user_id] = user.id
    # [:user_id]にログイン情報を保存
  end
  
  def log_out
    session.delete(:user_id)
    # セッションに保存されているuser_idを削除＝ログアウト
    @current_user = nil
    # ユーザー情報の削除
  end
  
  def email_params  # ★課題
    params.require(:session).permit(:email)
  end
  
  def password_params  # ★課題
    params.require(:session).permit(:password)
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    #binding.pry
    
    @topics = Topic.all.includes(:favorite_users)
  end
  
  def new
    @topic = Topic.new
  end
  
  def create
    @topic = current_user.topics.new(topic_params)
    
    if @topic.save
      redirect_to topics_path, success: '投稿に成功しました'
      
    else
      flash.now[:danger] = "投稿に失敗しました"
      render :new
    end
  end
    
    private
    def topic_params
      params.require(:topic).permit(:image, :description)
    end
end

app/controllers/users_controller.rb
# ユーザー情報の登録
# view/users/new.html.erb　9行目に紐づく@userインスタンス変数を定義している
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  # モデルを新規
  
  def create
    # binding.pry
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, success: '登録が完了しました'
    else
      flash.now[:danger] = "登録に失敗しました"
      render :new
    end
  end
  
  private # クラス外部から呼び出せないようにする
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/index.html.erb
class CommentController < ApplicationController
  def

app/views/comments/new.html.erb
<!--コメント投稿ページ-->

<div class="comment-new-wrapper" >
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">Add Comment</h1>
        
          <%= form_for @comment do |f| %>
            
            <div class="form-group">
              <%= f.label :comment %>
              <%= f.text_area :description, class: 'form-control'  %>
            </div>
            
            <% if logged_in? %> 
              <%= f.submit 'コメントする', class: 'btn btn-black btn-block' %>
            <% end %>
          
         <% end %>
      </div>
    </div>
  </div>
</div>

app/views/favorites/index.html.erb
<!--お気に入りの投稿一覧ページ-->

<div class="topic-index-wrapper">
  <div class="container">
    <% @favorite_topics.each do |topic| %>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="topic-index-single">
            <h2 class="topic-author">
              <%= topic.user.name %>
            </h2>
            <%= image_tag topic.image.url %>
            <%= image_tag 'icons/comment.png', class: 'topic-index-icon' %>
            <p class="topic-text">
              <%= topic.description %>
            </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!--画面共通で使用するHTMLを記載する-->

<!DOCTYPE html>
<html>
  <head>
    <title>Pictgram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>" role="alert"><%= value %></div>
    <% end %>
    
    <nav class="navbar navbar-default navbar-fixed-top navbar-transparent">
      <div class="container">
        <%= link_to root_path do %>
          <span><%= image_tag "icons/logo.png", class: "navbar-brand" %></span>
        <% end %>
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li>
              <%= link_to favorites_index_path do %>
                <%= image_tag "icons/heart.png" %>
              <% end %>
            </li>
            <li>
              <%= link_to new_topic_path do %>
                <%= image_tag "icons/camera.png" %>
              <% end %>
            </li>
            <li>
              <%= link_to logout_path, method: :delete do %>
                <%= image_tag "icons/logout.png" %>
              <% end %>
            </li>
          <% else %>
            <li>
              <%= link_to new_user_path do %>
                <%= image_tag "icons/register.png" %>
              <% end %>
            </li>
            <li>
              <%= link_to login_path do %>
                <%= image_tag "icons/login.png" %>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
    
    
    <%= yield %>
    
    <script>
      $(function(){
        $(".alert").fadeOut(5000);
      });
    </script>
  </body>
</html>

app/views/pages/help.html.erb
<h1>ヘルプページです</h1>

app/views/pages/index.html.erb
<!--トップページ-->

<div class="top-hero-wrapper text-center">
    <div class="container top-hero-container">
        <h1 class="text-white">Make you Happy</h1>
        <h2 class="text-white">Pictgram is a service that you can post photos.</h2>
        <p class="text-white">Let's make your account and log in it.</p>
        <div class="row">
          <div class="col-md-offset-3 col-md-3">
              <%= link_to 'Sign up', new_user_path, class: 'btn btn-block btn-white' %>
          </div>
          <div class="col-md-3">
              <%= link_to 'Log in', login_path, class: 'btn btn-block btn-white' %>
          </div>
        </div>
    </div>
</div>

app/views/topics/index.html.erb
<!--投稿した写真の一覧ページ-->

<div class ="topic-index-wrapper">
  <div class="container">
    <% @topics.each do |topic| %>
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div class="topic-index-single">
          <h2 class="topic-author">
            <%= topic.user.name %>
          </h2>
          
          <%= image_tag topic.image.url %>
          
          <% if !topic.favorite_users.include?(current_user) %>
          
            <%= link_to favorites_path(topic_id: topic.id), method: :post do %>
              <%= image_tag 'icons/heart-black.png', class: 'topic-unlike-icon' %>
              
            <% end %>
            
          <% else %>
            <%= link_to favorites_path(topic_id: topic.id), method: :delete do %>
              <%= image_tag 'icons/heart-black.png', class: 'topic-like-icon' %>
              
            <% end %>
            
          <% end %>
          
          <%= topic.favorite_users.count %>
          
          <%= link_to new_comment_path(topic_id: topic.id) do %>
            <%= image_tag 'icons/comment.png', class: 'topic-index-icon' %>
          <% end %>
          
          <p class="topic-text">
            <%= topic.description %>
          </p>
          
            <h4 class="topic-comment">コメント</h4>
              <% topic.comments.each do |comment| %>
            <p><%= comment.content %></p>
              <% end %>
          
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/topics/new.html.erb
<!--写真投稿ページ-->

<div class="topic-new-wrapper" >
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">Add Picture</h1>
        
          <%= form_for @topic do |f| %>
          
            <div class="form-group">
              <%= f.label :image %>
              <%= f.file_field :image %>
            </div>
            
            <div class="form-group">
              <%= f.label :description %>
              <%= f.text_area :description, class: 'form-control'  %>
            </div>
            
            <% if logged_in? %> <!--課題-->
              <%= f.submit '投稿', class: 'btn btn-black btn-block' %>
            <% end %>
          
         <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<!--ユーザーアカウント登録ページ -->

<div class="users-new-wrapper">
  <div class="container">
    <div class="row">
      <div class= "col-md-offset-4 col-md-4 users-new-container">
        <h1 class= "text-center text-white">Sign in</h1>
        
        <%= form_for @user do |f| %>　<!--userの各カラム情報を入力、更新する-->
          <div class="form-group">
            <%= f.label :name, class: 'text-white' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :email, class: 'text-white' %>
            <%= f.text_field :email, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password, class: 'text-white' %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :pasword_confirmation, class: 'text-white' %>
            <%= f.password_field :pasword_confirmation, class: 'form-control' %>
          </div>

          <%= f.submit "登録", class: 'btn-block btn-white' %>
          <!--f.submit：送信ボタンの生成-->
        <% end %>
          
        <%= link_to 'ログインはこちら', login_path, class: 'text-white' %>
      </div>
    </div>
  </div>
</div>